ERROR : remove USE RESP_M statement
getting error:
mgblk.F:1699.23:

     $                 chdw,swetw,fmdotw,

Error: Rank mismatch in argument 'hdw' at (1) (scalar and rank-1)

mgblk.F:  chdw is declared as 1D array
resp.F :  chdw is declared as 2D array